-- Import existing products from products.ts
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard -> SQL Editor)
-- This will replace ALL existing products with the correct data

TRUNCATE TABLE products;

INSERT INTO products (name_sr, subtitle_sr, description_sr, story_sr, category, category_label_sr, price_rsd, original_price_rsd, lead_time_days, badge, sizes, features, materials_composition, materials_origin, materials_care, model_info, images, thumbnail, featured, active) VALUES

('Majica "Collage"', 'Lagana, providna majica za savršen morski look', 'Lagano, providno i chic, majica "Collage" za savršen morski look.', 'Inspirisana mediteranskim letom i laganim povetarcem, majica "Collage" je stvorena za žene koje uživaju u opuštenoj eleganciji.', 'majice', 'Majice', 2990, NULL, '2–3 radna dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)'],
ARRAY['Lagana, prozračna tkanina prijatna na koži', 'Chic dizajn idealan za letnje kombinacije', 'Savršena za morski look i opuštene dane', 'Može se nositi samostalno ili slojevito'],
'100% Poliester (mrežica)', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu M (38)',
ARRAY['/majice/collage/collage1.jpg', '/majice/collage/collage2.jpg', '/majice/collage/collage3.jpg'],
'/majice/collage/collage1.jpg', false, true),

('Haljina "Larisa"', '"Leto u boji mora"', 'Leto u boji mora. Haljina "Larisa" ističe vašu preplanulost i čini da izgledate zanosno bez napora.', 'Inspirisana bojama Jonskog mora i letnjim zalascima sunca, haljina "Larisa" je stvorena za žene koje žele da zablistaju bez napora.', 'haljine', 'Letnje haljine', 7990, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Lagana, lepršava tkanina prijatna na koži', 'Boja koja ističe preplanulost', 'Zanosan izgled bez napora', 'Idealna za letnje večeri i posebne prilike'],
'100% Prirodna tkanina, pamuk', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 178 cm i nosi veličinu M (38)',
ARRAY['/haljine/larisa/larisa1.jpg', '/haljine/larisa/larisa2.jpg', '/haljine/larisa/larisa3.jpg'],
'/haljine/larisa/larisa1.jpg', true, true),

('Suknja "Joli Suki"', 'Minimalistička suknja sa jednom nogavicom', '"Joli Suki" je minimalizam koji ne traži pažnju, ona je privlači. Suknja sa jednom nogavicom ne prati pravila, već ih postavlja.', 'Dizajnirana za žene koje ne prate trendove već ih kreiraju. "Joli Suki" ruši konvencije asimetričnom formom i čistim linijama.', 'suknje', 'Suknje', 5990, NULL, '3–5 radnih dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Asimetričan kroj sa jednom nogavicom', 'Minimalistički dizajn koji privlači pažnju', 'Čiste linije i precizna izrada', 'Savršena za kombinovanje sa različitim gornjim delovima'],
'50% Viskoza 50% Poliester (Žersej)', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 176 cm i nosi veličinu L (40)',
ARRAY['/suknje/jolisuki/jolisuki1.jpg', '/suknje/jolisuki/jolisuki2.jpg', '/suknje/jolisuki/jolisuki3.jpg'],
'/suknje/jolisuki/jolisuki1.jpg', false, true),

('Haljina "Olivia"', 'Klasična prugasta haljina za opušten letnji look', 'Najudobnija haljina koju ćeš nositi ove sezone! Haljina "Olivia" je savršen spoj stila i udobnosti. Prugicie joj daju onaj klasičan letnji izgled, a kroj je super opušten!', 'Stvorena za dane kada želite da izgledate sjajno a osećate se još bolje. "Olivia" je haljina u kojoj ćete provoditi ceo dan — od jutarnje kafe do večernje šetnje.', 'haljine', 'Letnje haljine', 7990, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Klasičan prugast dizajn za bezvremeni letnji look', 'Super opušten kroj za maksimalnu udobnost', 'Lagana tkanina prijatna na koži', 'Idealna za svakodnevno nošenje i letnja putovanja'],
'50% Viskoza 50% Poliester', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu L (40)',
ARRAY['/haljine/olivia/olivia1.jpg'],
'/haljine/olivia/olivia1.jpg', false, true),

('Top "Jullyet"', 'Bezrukava top sa leopard dezenom i tilom', 'Tražite savršenu kombinaciju odvažnog i elegantnog? Top "Jullyet" bez rukava donosi atraktivan sivo crni leopard dezen kombinovan sa sofisticiranim crnim tilom na bočnim stranama koji stvara lagan i lepršav efekat.', 'Kombinacija divljeg leopard printa i nežnog tila — "Jullyet" je za žene koje ne boje da budu primećene.', 'majice', 'Majice', 4490, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)'],
ARRAY['Atraktivan sivo-crni leopard dezen', 'Sofisticirani crni til na bočnim stranama', 'Lagan i lepršav efekat', 'Bezrukavni kroj za letnje dane'],
'Pamučni saten + til', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 176 cm i nosi veličinu M (38)',
ARRAY['/majice/jullyet/jullyet1.jpg'],
'/majice/jullyet/jullyet1.jpg', false, true),

('Haljina "Rahela"', 'Bezvremenska elegancija u crno-belim tufnama', 'Obuci "Rahela" haljinu na koktel, večeru ili letnju zabavu i budi zvezda večeri. Crno-bela tkanina sa tufnama kreira sofisticiran i bezvremenski look koji nikad ne izlazi iz mode.', 'Inspirisana klasičnim filmskim herojinama i bezvremenom elegancijom, "Rahela" je stvorena za žene koje žele da zablistaju na svakoj prilici bez mnogo napora.', 'haljine', 'Letnje haljine', 9990, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Crno-bela tkanina sa elegantnim tufnama', 'Savršena za koktel, večeru i letnje zabave', 'Bezvremenski kroj koji lepote svaku figuru', 'Lagan i udoban materijal za celodnevno nošenje'],
'50% Viskoza 50% Poliester', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu M (38)',
ARRAY['/haljine/rahela/rahela1.jpg', '/haljine/rahela/rahela2.jpg'],
'/haljine/rahela/rahela1.jpg', true, true),

('Letnja lanena haljina "Mare"', 'Spremna za sunce uz more', 'Savršena letnja haljina (100% lan, 100% unikat), idealna za lagane letnje šetnje. Dodajte samo pletenu torbu i omiljene sandale i spremne ste za sunčan letnji dan.', 'Inspirisana mediteranskim letnjim danima i povetarcem uz obalu. "Mare" je stvorena za žene koje cene prirodne materijale i bezrežimski komfor.', 'haljine', 'Letnje haljine', 9990, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['100% prirodan lan - dišuća i hladna tkanina', 'Jedinstven unikat - svaka haljina je zaista posebna', 'Opušten kroj za maksimalnu slobodu pokreta', 'Idealna za plažu, grad i putovanja'],
'100% Prirodan lan', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja dok je vlažno', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu L (40)',
ARRAY['/haljine/letnja01/letnja1.jpg'],
'/haljine/letnja01/letnja1.jpg', true, true),

('Crvena asimetrična haljina "Linda"', 'Crvena nije samo boja, to je energija, strast i samopouzdanje', 'Crvena nije samo boja, to je energija, strast i samopouzdanje koje nosite. Osetite tu moć u ovoj spektakularnoj asimetričnoj haljini, gde je svaki šav priča za sebe.', 'Dizajnirana za žene koje ne boje da budu u centru pažnje. "Linda" spaja odvažan asimetričan kroj sa senzualnošću crvene boje, kreirajući haljinu koja govori pre nego što vi progovorite.', 'haljine', 'Večernje haljine', 9990, NULL, '3–5 radnih dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Spektakularan asimetričan kroj', 'Intenzivna crvena boja za maksimalan uticaj', 'Svaki šav pažljivo odrađen ručno', 'Idealna za večerne izlazke i posebne prilike'],
'100% Prirodna pamuk', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu L (40)',
ARRAY['/haljine/crvena01/crvena1.jpg'],
'/haljine/crvena01/crvena1.jpg', false, true),

('Haljina "Žozefin"', 'Balans između prefinjenosti i modernog dizajna', 'Haljina "Žozefin" deluje kao savršen izbor za prilike gde se traži balans između prefinjenosti i modernog dizajna.', 'Inspiracija za "Žozefin" dolazi iz želje da se spoji klasika sa modernim detaljima. Ova haljina je za žene koje cene eleganciju ali ne žele da žrtvuju svoj jedinstveni stil.', 'haljine', 'Večernje haljine', 8990, NULL, 'Odmah dostupno', 'LIMITED EDITION',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Prefinjen dizajn sa modernim detaljima', 'Balans klase i savremenog stila', 'Izrađena od kvalitetnih materijala', 'Idealna za posebne prilike i svečane događaje'],
'50% Viskoza 50% Poliester', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu M (38)',
ARRAY['/haljine/zozelin/zozelin1.jpg'],
'/haljine/zozelin/zozelin1.jpg', false, true),

('Unikatna haljina "Linda"', 'Asimetrični kroj i prefinjena silueta u boji peska', 'Ova unikatna haljina u boji peska, spaja asimetrični kroj i prefinjenu siluetu, čineći je idealnim izborom za svaku priliku gde želite da ostavite utisak bez mnogo truda.', 'Svaka unikatna haljina priča svoju priču. "Pesak" je inspirisan prirodnim tonovima i asimetričnim formama koje ističu žensku senzualnost na sofisticiran način.', 'haljine', 'Letnje haljine', 9990, NULL, '5–7 radnih dana', 'Novo',
ARRAY['Izrada po ličnim merama'],
ARRAY['Jedinstven unikat - samo jedan komad', 'Asimetrični kroj koji ističe siluetu', 'Elegantna boja peska', 'Prefinjena izrada sa pažnjom na detalje'],
'100% Prirodna pamuk', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 176 cm i nosi veličinu L (40)',
ARRAY['/haljine/unikatna/unikatna1.jpg'],
'/haljine/unikatna/unikatna1.jpg', false, true),

('Crna asimetrična haljina "Linda"', 'Više od haljine - to je tvoja supermoć', 'Više od haljine! To je tvoja supermoć. Ovaj asimetrični kroj nije za stidljive. To je komad za ženu koja zna šta želi i ne plaši se da to pokaže.', 'Za ženu koja se usuđuje da bude drugačija. Crna asimetrična haljina je više od odeće - to je izjava. Komad koji govori vašim jezikom pre nego što vi progovorite.', 'haljine', 'Letnje haljine', 9990, NULL, '3–5 radnih dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Odvažan asimetrični kroj', 'Intenzivna crna boja', 'Za ženu koja zna šta želi', 'Komad koji ostavlja utisak'],
'100% Prirodna pamuk', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu L (40)',
ARRAY['/haljine/crna/crna1.jpg'],
'/haljine/crna/crna1.jpg', false, true),

('Haljina "Linda"', 'Burgundi asimetrična kreacija', 'Haljina koja govori pre nego što progovorite. Otkrijte lepotu asimetrije u burgundi kreaciji. Izrađena s ljubavlju i pažnjom prema svakom detalju.', '"Linda" je više od odeće, to je izjava o stilu. Inspiracija dolazi iz želje da se spoji toplina burgundi boje sa modernim asimetričnim krojem koji ostavlja bez daha.', 'haljine', 'Letnje haljine', 9990, NULL, '4–6 radnih dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Elegantna burgundi boja', 'Asimetrični kroj za dramatičan efekat', 'Izrađena s ljubavlju i pažnjom prema svakom detalju', 'Izjava o stilu'],
'100% Prirodna pamuk', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 177 cm i nosi veličinu L (40)',
ARRAY['/haljine/linda/linda1.jpg'],
'/haljine/linda/linda1.jpg', false, true),

('Jakna "Gaby"', 'Teal-plava jakna od italijanske kože', 'Teal-plava jakna "Gaby" od italijanske kože (poznate po mekoći, dugovečnosti i luksuznom sjaju), prilagođava se telu i vremenom postaje sve lepša.', 'To je komad koji ne samo da gradi stil, već i priču o kvalitetu, trajnosti i sofisticiranom ukusu. Italijanska koža je poznata po svojoj mekoći i dugovečnosti, a jakna "Gaby" to potvrđuje.', 'blejzeri', 'Blejzeri i jakne', 14990, NULL, 'DOSTUPNO ODMAH', '1 of 1',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)'],
ARRAY['Italijanska koža vrhunskog kvaliteta', 'Teal-plava boja za sofisticiran izgled', 'Prilagođava se telu vremenom', 'Komad koji traje ceo život'],
'100% Italijanska koža', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Čistiti kod stručnog kozmetičara za kožu', 'Redovno tretirati sredstvom za kožu', 'Čuvati na suvom mestu'],
'Model je visoka 176 cm i nosi veličinu M (38)',
ARRAY['/blejzeri/gaby/gaby1.jpg'],
'/blejzeri/gaby/gaby1.jpg', true, true),

('Tunika "Atina"', 'Nežnost i snaga u asimetričnom kroju', 'Tunika "Atina" ukazuje na nežnost i snagu istovremeno. Asimetrični kroj i nabori pretvaraju je u umetnost. Ne pripada serijskoj, brzoj proizvodnji.', 'Ona je plod mog ručnog rada, strpljenja i emocije, namenjena svima koji vole unikatno šivenu odeću. "Atina" je inspirisana grčkom lepotom i snagom žene.', 'tunike', 'Tunike', 5990, NULL, '4–6 radnih dana', 'Novo',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Asimetrični kroj sa elegantnim naborima', 'Nežnost i snaga u jednom komadu', 'Ručni rad sa puno pažnje', 'Unikatna izrada'],
'100% viskoza (žersej)', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 175 cm i nosi veličinu L (40)',
ARRAY['/haljine/atina/atina1.jpg', '/haljine/atina/atina2.jpg'],
'/haljine/atina/atina1.jpg', false, true),

('Pačvork haljina "Kaliope"', 'Boje i geometrija u jednoj priči', '"Kaliope" pačvork haljina spaja boje i geometriju u jednu priču. Asimetrični kroj i smeli kontrasti, pretvaraju je u modni manifest.', 'Ona je hrabra, umetnička i neponovljiva. Ona je jedna i jedina. "Kaliope" je inspirisana umetnošću pačvorka i željom da se stvori komad koji je istovremeno nosiv i umetnički.', 'haljine', 'Haljine', 10490, NULL, '5–7 radnih dana', 'UNIKAT',
ARRAY['XS (34)', 'S (36)', 'M (38)', 'L (40)', 'XL (42)', 'Izrada po ličnim merama'],
ARRAY['Jedinstven pačvork dizajn', 'Smeli kontrasti i geometrijski oblici', 'Asimetrični kroj za moderan izgled', 'Hrabra i umetnička kreacija'],
'100% viskoza', 'Ručno šiveno u Ateljeu Jelena Erić, Topola',
ARRAY['Pranje u mašini na 30°C', 'Peglati sa naličja', 'Ne sušiti u mašini'],
'Model je visoka 178 cm i nosi veličinu L (40)',
ARRAY['/haljine/kaliope/kaliope1.jpg', '/haljine/kaliope/kaliope2.jpg', '/haljine/kaliope/kaliope3.jpg', '/haljine/kaliope/kaliope4.jpg'],
'/haljine/kaliope/kaliope1.jpg', true, true);
